(function(){var h={},mt={},c={id:"6cda846867fd596b2ca7a177bac2039f",dm:["app.ggzhuansha.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'',ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,aet:'',hca:'267134B2DD1855CF',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var q=void 0,r=!0,s=null,t=!1;mt.cookie={};mt.cookie.set=function(b,a,d){var l;d.B&&(l=new Date,l.setTime(l.getTime()+d.B));document.cookie=b+"="+a+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(l?"; expires="+l.toGMTString():"")+(d.Kb?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:s};
mt.cookie.gb=function(b,a){try{var d="Hm_ck_"+ +new Date;mt.cookie.set(d,"is-cookie-enabled",{domain:b,path:a,B:q});var l="is-cookie-enabled"===mt.cookie.get(d)?"1":"0";mt.cookie.set(d,"",{domain:b,path:a,B:-1});return l}catch(f){return"0"}};mt.lang={};mt.lang.d=function(b,a){return"[object "+a+"]"==={}.toString.call(b)};mt.lang.ta=function(b){return mt.lang.d(b,"Number")&&isFinite(b)};mt.lang.ba=function(){return mt.lang.d(c.aet,"String")};
mt.lang.j=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.D=function(b,a){var d=t;if(b==s||!mt.lang.d(b,"Array")||a===q)return d;if(Array.prototype.indexOf)d=-1!==b.indexOf(a);else for(var l=0;l<b.length;l++)if(b[l]===a){d=r;break}return d};
(function(){var b=mt.lang;mt.e={};mt.e.Oa=function(a){return document.getElementById(a)};mt.e.$=function(a,d){var b=[],f=[];if(!a)return f;for(;a.parentNode!=s;){for(var g=0,n=0,m=a.parentNode.childNodes.length,e=0;e<m;e++){var k=a.parentNode.childNodes[e];if(k.nodeName===a.nodeName&&(g++,k===a&&(n=g),0<n&&1<g))break}if((m=""!==a.id)&&d){b.unshift("#"+encodeURIComponent(a.id));break}else m&&(m="#"+encodeURIComponent(a.id),m=0<b.length?m+">"+b.join(">"):m,f.push(m)),b.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+
(1<g?"["+n+"]":""));a=a.parentNode}f.push(b.join(">"));return f};mt.e.Ua=function(a){return(a=mt.e.$(a,r))&&a.length?String(a[0]):""};mt.e.Fb=function(a){return mt.e.$(a,t)};mt.e.Db=function(a,d){for(d=d.toUpperCase();(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return s};mt.e.Pa=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.e.Eb=function(a){var d={top:0,left:0};if(!a)return d;var b=mt.e.Pa(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(d=a.getBoundingClientRect());
return{top:d.top+(window.pageYOffset||b.scrollTop)-(b.clientTop||0),left:d.left+(window.pageXOffset||b.scrollLeft)-(b.clientLeft||0)}};mt.e.getAttribute=function(a,b){var l=a.getAttribute&&a.getAttribute(b)||s;if(!l&&a.attributes&&a.attributes.length)for(var f=a.attributes,g=f.length,n=0;n<g;n++)f[n].nodeName===b&&(l=f[n].nodeValue);return l};mt.e.L=function(a){var b="document";a.tagName!==q&&(b=a.tagName);return b.toLowerCase()};mt.e.Wa=function(a){var d="";a.textContent?d=b.trim(a.textContent):
a.innerText&&(d=b.trim(a.innerText));d&&(d=d.replace(/\s+/g," ").substring(0,255));return d};mt.e.Qa=function(a){var b=mt.e.L(a);"input"===b&&("button"===a.type||"submit"===a.type)?a=a.value||"":"img"===b?(b=mt.e.getAttribute,a=b(a,"alt")||b(a,"title")||b(a,"src")):a="body"===b||"html"===b?["(hm-default-content-for-",b,")"].join(""):mt.e.Wa(a);return String(a).substring(0,255)};(function(){(mt.e.ib=function(){function a(){if(!a.O){a.O=r;for(var b=0,d=f.length;b<d;b++)f[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(l){setTimeout(b,
1);return}a()}var l=t,f=[],g;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,t);a()}:document.attachEvent&&(g=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",g),a())});(function(){if(!l)if(l=r,"complete"===document.readyState)a.O=r;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",g,t),window.addEventListener("load",a,t);else if(document.attachEvent){document.attachEvent("onreadystatechange",
g);window.attachEvent("onload",a);var f=t;try{f=window.frameElement==s}catch(m){}document.documentElement.doScroll&&f&&b()}})();return function(b){a.O?b():f.push(b)}}()).O=t})();return mt.e})();mt.event={};mt.event.c=function(b,a,d){b.attachEvent?b.attachEvent("on"+a,function(a){d.call(b,a)}):b.addEventListener&&b.addEventListener(a,d,t)};mt.event.preventDefault=function(b){b.preventDefault?b.preventDefault():b.returnValue=t};
(function(){var b=mt.event;mt.g={};mt.g.sa=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.g.eb=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:q;mt.g.cookieEnabled=navigator.cookieEnabled;mt.g.javaEnabled=navigator.javaEnabled();mt.g.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.g.lb=(window.screen.width||0)+"x"+(window.screen.height||0);mt.g.colorDepth=window.screen.colorDepth||0;mt.g.M=function(){var a;
a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.g.C=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.g.orientation=0;(function(){function a(){var a=0;window.orientation!==q&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==q)&&(a=screen.orientation.angle);mt.g.orientation=a}a();b.c(window,"orientationchange",a)})();return mt.g})();
mt.l={};mt.l.parse=function(){return(new Function('return (" + source + ")'))()};
mt.l.stringify=function(){function b(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=d[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function a(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return b(d);case "boolean":return String(d);
default:if(d===s)return"null";if(d instanceof Array){var f=["["],g=d.length,n,m,e;for(m=0;m<g;m++)switch(e=d[m],typeof e){case "undefined":case "function":case "unknown":break;default:n&&f.push(","),f.push(mt.l.stringify(e)),n=1}f.push("]");return f.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+a(d.getMonth()+1)+"-"+a(d.getDate())+"T"+a(d.getHours())+":"+a(d.getMinutes())+":"+a(d.getSeconds())+'"';n=["{"];m=mt.l.stringify;for(g in d)if(Object.prototype.hasOwnProperty.call(d,g))switch(e=
d[g],typeof e){case "undefined":case "unknown":case "function":break;default:f&&n.push(","),f=1,n.push(m(g)+":"+m(e))}n.push("}");return n.join("")}}}();mt.localStorage={};mt.localStorage.R=function(){if(!mt.localStorage.i)try{mt.localStorage.i=document.createElement("input"),mt.localStorage.i.type="hidden",mt.localStorage.i.style.display="none",mt.localStorage.i.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.i)}catch(b){return t}return r};
mt.localStorage.set=function(b,a,d){var l=new Date;l.setTime(l.getTime()+d||31536E6);try{window.localStorage?(a=l.getTime()+"|"+a,window.localStorage.setItem(b,a)):mt.localStorage.R()&&(mt.localStorage.i.expires=l.toUTCString(),mt.localStorage.i.load(document.location.hostname),mt.localStorage.i.setAttribute(b,a),mt.localStorage.i.save(document.location.hostname))}catch(f){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var a=b.indexOf("|"),d=b.substring(0,a)-0;if(d&&d>(new Date).getTime())return b.substring(a+1)}}else if(mt.localStorage.R())try{return mt.localStorage.i.load(document.location.hostname),mt.localStorage.i.getAttribute(b)}catch(l){}return s};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.R())try{mt.localStorage.i.load(document.location.hostname),mt.localStorage.i.removeAttribute(b),mt.localStorage.i.save(document.location.hostname)}catch(a){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,a){if(window.sessionStorage)try{window.sessionStorage.setItem(b,a)}catch(d){}};
mt.sessionStorage.get=function(b){return window.sessionStorage?window.sessionStorage.getItem(b):s};mt.sessionStorage.remove=function(b){window.sessionStorage&&window.sessionStorage.removeItem(b)};mt.xa={};mt.xa.log=function(b,a){var d=new Image,l="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[l]=d;d.onload=d.onerror=d.onabort=function(){d.onload=d.onerror=d.onabort=s;d=window[l]=s;a&&a(b)};d.src=b};mt.ia={};
mt.ia.Xa=function(){var b="";if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];a&&a.description&&(b=a.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(b=a.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(d){}return b};
mt.ia.Cb=function(b,a,d,l,f){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+b+'" width="'+d+'" height="'+l+'"><param name="movie" value="'+a+'" /><param name="flashvars" value="'+(f||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+b+'" width="'+d+'" height="'+l+'" src="'+a+'" flashvars="'+(f||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.k=function(b,a){var d=b.match(RegExp("(^|&|\\?|#)("+a+")=([^&#]*)(&|$|#)",""));return d?d[3]:s};mt.url.Gb=function(b){return(b=b.match(/^(https?:)\/\//))?b[1]:s};mt.url.Sa=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):s};mt.url.Z=function(b){return(b=mt.url.Sa(b))?b.replace(/:\d+$/,""):b};mt.url.$=function(b){return(b=b.match(/^(https?:\/\/)?[^\/]*(.*)/))?b[2].replace(/[\?#].*/,"").replace(/^$/,"/"):s};
(function(){function b(){for(var a=t,b=document.getElementsByTagName("script"),l=b.length,l=100<l?100:l,f=0;f<l;f++){var g=b[f].src;if(g&&0===g.indexOf("https://hm.baidu.com/h")){a=r;break}}return a}return h.Na=b})();var A=h.Na;
h.o={Hb:"http://tongji.baidu.com/hm-web/welcome/ico",wa:"hm.baidu.com/hm.gif",Ca:"tongji.baidu.com",ab:"hmmd",bb:"hmpl",wb:"utm_medium",$a:"hmkw",yb:"utm_term",Ya:"hmci",vb:"utm_content",cb:"hmsr",xb:"utm_source",Za:"hmcu",ub:"utm_campaign",w:0,s:Math.round(+new Date/1E3),z:Math.round(+new Date/1E3)%65535,protocol:"https:"===document.location.protocol?"https:":"http:",da:A()||"https:"===document.location.protocol?"https:":"http:",Ib:0,Ab:6E5,hb:6E5,Jb:5E3,Bb:5,V:1024,zb:1,ea:2147483647,ya:"hca bs kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn ct u tt hh".split(" "),
F:r,oa:["a","input","button"],Ea:{id:"data-hm-id",U:"data-hm-class",la:"data-hm-xpath",content:"data-hm-content",Q:"data-hm-tag",link:"data-hm-link"},na:"data-hm-enabled",ma:"data-hm-disabled"};(function(){var b={p:{},c:function(a,b){this.p[a]=this.p[a]||[];this.p[a].push(b)},J:function(a,b){this.p[a]=this.p[a]||[];for(var l=this.p[a].length,f=0;f<l;f++)this.p[a][f](b)}};return h.A=b})();
(function(){function b(b,l){var f=document.createElement("script");f.charset="utf-8";a.d(l,"Function")&&(f.readyState?f.onreadystatechange=function(){if("loaded"===f.readyState||"complete"===f.readyState)f.onreadystatechange=s,l()}:f.onload=function(){l()});f.src=b;var g=document.getElementsByTagName("script")[0];g.parentNode.insertBefore(f,g)}var a=mt.lang;return h.load=b})();
(function(){var b=mt.lang,a=mt.e,d=mt.event,l=mt.g,f=h.o,g=h.A,n=+new Date,m=[],e={pa:function(){return function(k){if(h.b&&h.b.F&&c.aet&&c.aet.length){var d=k.target||k.srcElement;if(d){var g=h.b.oa,p=a.getAttribute(d,f.na)!=s?r:t;if(a.getAttribute(d,f.ma)==s)if(p)e.S(e.Y(d,k));else{var u=a.L(d);if(b.D(g,"*")||b.D(g,u))e.S(e.Y(d,k));else for(;d.parentNode!=s;){var p=d.parentNode,u=a.L(p),x="a"===u&&b.D(g,"a")?r:t,u="button"===u&&b.D(g,"button")?r:t,y=a.getAttribute(p,f.na)!=s?r:t;if(a.getAttribute(p,
f.ma)==s&&(x||u||y)){e.S(e.Y(p,k));break}d=d.parentNode}}}}}},Y:function(k,d){var e={},p=f.Ea;e.id=a.getAttribute(k,p.id)||a.getAttribute(k,"id")||"";e.U=a.getAttribute(k,p.U)||a.getAttribute(k,"class")||"";e.la=a.getAttribute(k,p.la)||a.Ua(k);e.content=a.getAttribute(k,p.content)||a.Qa(k);e.Q=a.getAttribute(k,p.Q)||a.L(k);e.link=a.getAttribute(k,p.link)||a.getAttribute(k,"href")||"";e.type=d.type||"click";p=b.ta(k.offsetTop)?k.offsetTop:0;"click"===d.type?p=l.sa?d.clientY+Math.max(document.documentElement.scrollTop,
document.body.scrollTop):d.pageY:"touchend"===d.type&&(d.fa&&b.d(d.fa.changedTouches,"Array")&&d.fa.changedTouches.length)&&(p=d.fa.changedTouches[0].pageY);e.tb=p;return e},S:function(k){var a=b.j,a=[+new Date-(h.b.r!==q?h.b.r:n),a(k.id),a(k.U),a(k.Q),a(k.la),a(k.link),a(k.content),k.type,k.tb].join("*");e.T(a);b.D(["a"],k.Q)&&b.d(this.H(),"Function")&&this.H()()},T:function(a){a.length>f.V||(encodeURIComponent(m.join("!")+a).length>f.V&&(e.I(m.join("!")),m=[]),m.push(a))},I:function(a){h.b.a.et=
5;h.b.a.ep=a;h.b.h()},H:function(){return function(){m&&m.length&&(e.I(m.join("!")),m=[])}}};b.ba()&&""!==c.aet&&g.c("pv-b",function(){d.c(document,"click",e.pa());"ontouchend"in document&&d.c(window,"touchend",e.pa());d.c(window,"unload",e.H())});return e})();
(function(){var b=mt.event,a=mt.g,d=h.o,l=h.A,f=+new Date,g=[],n=s,m={Ja:function(){return function(){h.b&&(h.b.F&&c.aet&&c.aet.length)&&(window.clearTimeout(n),n=window.setTimeout(function(){m.Aa(a.M()+a.C())},150))}},Aa:function(a){m.T([+new Date-(h.b.r!==q?h.b.r:f),a].join("*"))},T:function(a){if(encodeURIComponent(g.join("!")+a).length>d.V||5<g.length)m.I(g.join("!")),g=[];g.push(a)},I:function(b){h.b.a.et=6;h.b.a.vh=a.C();h.b.a.ep=b;h.b.h()},H:function(){return function(){g&&g.length&&(m.I(g.join("!")),
g=[])}}};mt.lang.ba()&&""!==c.aet&&l.c("pv-b",function(){b.c(window,"scroll",m.Ja());b.c(window,"unload",m.H())});return m})();
(function(){function b(){function a(b){function d(){}for(var k=r,g=0,l=0,p=s,u=s,x=b.length,y=0,z=s,g=0;g<x;g++)if(p=b[g],p.chromeVer===n){k=r;u=p.tests;y=u.length;for(l=0;l<y;l++)if(d=f[u[l].name],d()!==u[l].expect){k=t;break}if(y&&k){z={name:"360browser",type:p.type,version:p.ver};break}}return z}var b=[];b.push({ver:"8.3",type:"fast",tests:[{name:"seamlessiframe",expect:1}],chromeVer:"42"});var f={pointerevents:function(){return"maxTouchPoints"in window.navigator?1:"msMaxTouchPoints"in window.navigator||
"mozMaxTouchPoints"in window.navigator||"webkitMaxTouchPoints"in window.navigator?9:0},webgl3D:function(){for(var a="webgl ms-webgl experimental-webgl moz-webgl opera-3d webkit-3d ms-3d 3d".split(" "),b=a.length,k="",d=document.createElement("canvas"),g=t,p=0;p<b;p++)try{if(d.getContext(a[p])){g=r;k=a[p];break}}catch(u){}return g?"webgl"===k?1:9:0},seamlessiframe:function(){return"seamless"in document.createElement("iframe")?1:0},speechsynthesis:function(){return"speechSynthesis"in window?1:"webkitSpeechSynthesis"in
window||"mozSpeechSynthesis"in window||"oSpeechSynthesis"in window||"msSpeechSynthesis"in window?9:0}},g=s,n=function(){var a=navigator.userAgent.toLowerCase().match(/chrome\/(\d+)/i);return a?a[1]:"-1"}();"-1"!==n&&(g=a(b));return g}var a=function(){var a=navigator.userAgent.toLowerCase();if(0<=a.indexOf("chrome")){var a=(a=a.match(/chrome\/(\d+)/))?a[1]:-1,l=window.document,f="track"in l.createElement("track"),l="scoped"in l.createElement("style"),g="v8Locale"in window,n=document.createElement("canvas"),
m="seamless"in document.createElement("iframe"),e=t;try{n.getContext("webgl")&&(e=r)}catch(k){}if(n=b())return"fast"===n.type?7:1;if(!e&&"31"===a)return 1;if(!(m=(m||!e)&&"38"===a))if(m=f)if(m=!l)if(m=!g){var v;a:{m=window.navigator.mimeTypes;for(v in m)if("application/vnd.chromium.remoting-viewer"===m[v].type){v=r;break a}v=t}m=!v&&46>+a}if(m)return 7;if(f&&l&&g)return 1}return-1}();return h.Fa=a})();
(function(){function b(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.W.Ta()+","+h.W.Ra();h.b.h()}}function a(){clearTimeout(z);var b;x&&(b="visible"==document[x]);y&&(b=!document[y]);m="undefined"==typeof b?r:b;if((!n||!e)&&m&&k)u=r,w=+new Date;else if(n&&e&&(!m||!k))u=t,p+=+new Date-w;n=m;e=k;z=setTimeout(a,100)}function d(a){var k=document,b="";if(a in k)b=a;else for(var p=["webkit","ms","moz","o"],d=0;d<p.length;d++){var e=p[d]+a.charAt(0).toUpperCase()+a.slice(1);if(e in k){b=
e;break}}return b}function l(b){if(!("focus"==b.type||"blur"==b.type)||!(b.target&&b.target!=window))k="focus"==b.type||"focusin"==b.type?r:t,a()}var f=mt.event,g=h.A,n=r,m=r,e=r,k=r,v=+new Date,w=v,p=0,u=r,x=d("visibilityState"),y=d("hidden"),z;a();(function(){var k=x.replace(/[vV]isibilityState/,"visibilitychange");f.c(document,k,a);f.c(window,"pageshow",a);f.c(window,"pagehide",a);"object"==typeof document.onfocusin?(f.c(document,"focusin",l),f.c(document,"focusout",l)):(f.c(window,"focus",l),
f.c(window,"blur",l))})();h.W={Ta:function(){return+new Date-v},Ra:function(){return u?+new Date-w+p:p}};g.c("pv-b",function(){f.c(window,"unload",b())});return h.W})();
(function(){var b=mt.lang,a=h.o,d=h.load,l={fb:function(f){if((window._dxt===q||b.d(window._dxt,"Array"))&&"undefined"!==typeof h.b){var g=h.b.K();d([a.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(g)].join(""),f)}},rb:function(a){if(b.d(a,"String")||b.d(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.Ha=l})();
(function(){function b(a,b,d,p){if(!(a===q||b===q||p===q)){if(""===a)return[b,d,p].join("*");a=String(a).split("!");for(var e,g=t,y=0;y<a.length;y++)if(e=a[y].split("*"),String(b)===e[0]){e[1]=d;e[2]=p;a[y]=e.join("*");g=r;break}g||a.push([b,d,p].join("*"));return a.join("!")}}function a(b){for(var e in b)if({}.hasOwnProperty.call(b,e)){var g=b[e];d.d(g,"Object")||d.d(g,"Array")?a(g):b[e]=String(g)}}var d=mt.lang,l=mt.l,f=mt.g,g=h.o,n=h.A,m=h.Ha,e={G:[],P:0,ua:t,m:{ka:"",page:""},init:function(){e.f=
0;n.c("pv-b",function(){e.Ia();e.La()});n.c("pv-d",function(){e.Ma();e.m.page=""});n.c("stag-b",function(){h.b.a.api=e.f||e.P?e.f+"_"+e.P:"";h.b.a.ct=[decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),e.m.ka,e.m.page].join("!")});n.c("stag-d",function(){h.b.a.api=0;e.f=0;e.P=0})},Ia:function(){var a=window._hmt||[];if(!a||d.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var k=arguments[b];d.d(k,"Array")&&(a.cmd[a.id].push(k),"_setAccount"===
k[0]&&(1<k.length&&/^[0-9a-f]{32}$/.test(k[1]))&&(k=k[1],a.id=k,a.cmd[k]=a.cmd[k]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},La:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,p=0,g=b.length;p<g;p++){var f=b[p];d.test(f[0])?e.G.push(f):e.ga(f)}a.cmd[c.id]={push:e.ga}},Ma:function(){if(0<e.G.length)for(var a=0,b=e.G.length;a<b;a++)e.ga(e.G[a]);e.G=s},ga:function(a){var b=a[0];if(e.hasOwnProperty(b)&&
d.d(e[b],"Function"))e[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(e.f|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],t===a||r===a))e.f|=2,h.b.qa=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){e.f|=4;h.b.a.et=0;h.b.a.ep="";h.b.a.vl=f.M()+f.C();h.b.a.kb=0;h.b.aa?(h.b.a.nv=0,h.b.a.st=4):h.b.aa=r;var b=h.b.a.u,d=h.b.a.su;h.b.a.u=g.protocol+"//"+document.location.host+a[1];e.ua||(h.b.a.su=document.location.href);h.b.h();h.b.a.u=b;
h.b.a.su=d;h.b.r=+new Date}},_trackEvent:function(a){2<a.length&&(e.f|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=d.j(a[1])+"*"+d.j(a[2])+(a[3]?"*"+d.j(a[3]):"")+(a[4]?"*"+d.j(a[4]):""),h.b.h())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],g=a[4]||3;if(0<b&&6>b&&0<g&&4>g){e.P++;for(var p=(h.b.a.cv||"*").split("!"),f=p.length;f<b-1;f++)p.push("*");p[b-1]=g+"*"+d.j(a[2])+"*"+d.j(a[3]);h.b.a.cv=p.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.b.setData("Hm_cv_"+
c.id,encodeURIComponent(a),c.age):h.b.jb("Hm_cv_"+c.id)}}},_setUserTag:function(a){if(!(3>a.length)){var e=d.j(a[1]);a=d.j(a[2]);if(e!==q&&a!==q){var g=decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),g=b(g,e,1,a);h.b.setData("Hm_ct_"+c.id,encodeURIComponent(g),c.age)}}},_setVisitTag:function(a){if(!(3>a.length)){var g=d.j(a[1]);a=d.j(a[2]);if(g!==q&&a!==q){var f=e.m.ka,f=b(f,g,2,a);e.m.ka=f}}},_setPageTag:function(a){if(!(3>a.length)){var g=d.j(a[1]);a=d.j(a[2]);if(g!==q&&a!==q){var f=e.m.page,
f=b(f,g,3,a);e.m.page=f}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"===a[1].charAt(0)?g.protocol+"//"+window.location.host+a[1]:a[1],e.ua=r)},_trackOrder:function(b){b=b[1];d.d(b,"Object")&&(a(b),e.f|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=l.stringify(b),h.b.h())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])e.f|=32,h.b.a.et=93,h.b.a.ep=a,h.b.h()},_trackRTPageview:function(b){b=b[1];d.d(b,"Object")&&(a(b),b=l.stringify(b),
512>=encodeURIComponent(b).length&&(e.f|=64,h.b.a.rt=b))},_trackRTEvent:function(b){b=b[1];if(d.d(b,"Object")){a(b);b=encodeURIComponent(l.stringify(b));var f=function(a){var b=h.b.a.rt;e.f|=128;h.b.a.et=90;h.b.a.rt=a;h.b.h();h.b.a.rt=b},n=b.length;if(900>=n)f.call(this,b);else for(var n=Math.ceil(n/900),p="block|"+Math.round(Math.random()*g.ea).toString(16)+"|"+n+"|",u=[],x=0;x<n;x++)u.push(x),u.push(b.substring(900*x,900*x+900)),f.call(this,p+u.join("|")),u=[]}},_setUserId:function(a){a=a[1];m.fb();
m.rb(a)},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],t===a||r===a))h.b.ra=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],t===a||r===a))h.b.F=a}};e.init();h.Da=e;return h.Da})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=r,this.a={},this.ra=this.qa=r,this.F=k.F,this.oa=f.ba()&&0<c.aet.length?c.aet.split(","):"",this.aa=t,this.init())}var a=mt.url,d=mt.xa,l=mt.ia,f=mt.lang,g=mt.cookie,n=mt.g,m=mt.localStorage,e=mt.sessionStorage,k=h.o,v=h.Fa,w=h.A;b.prototype={ca:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},va:function(a,b){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(b)},N:function(b){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.va(b,c.dm[d]))return r}else{var e=a.Z(b);if(e&&this.ca(e,c.dm[d]))return r}return t},K:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.ca(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},X:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.va(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+
"/"}return"/"},Va:function(){if(!document.referrer)return k.s-k.w>c.vdur?1:4;var b=t;this.N(document.referrer)&&this.N(document.location.href)?b=r:(b=a.Z(document.referrer),b=this.ca(b||"",document.location.hostname));return b?k.s-k.w>c.vdur?1:4:3},getData:function(a){try{return g.get(a)||e.get(a)||m.get(a)}catch(b){}},setData:function(a,b,d){try{g.set(a,b,{domain:this.K(),path:this.X(),B:d}),d?m.set(a,b,d):e.set(a,b)}catch(f){}},jb:function(a){try{g.set(a,"",{domain:this.K(),path:this.X(),B:-1}),
e.remove(a),m.remove(a)}catch(b){}},pb:function(){var a,b,d,e,f;k.w=this.getData("Hm_lpvt_"+c.id)||0;13===k.w.length&&(k.w=Math.round(k.w/1E3));b=this.Va();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<k.s-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.s);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=k.s,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,
k.s);d=g.gb(this.K(),this.X());if(0===c.nv&&this.N(document.location.href)&&(""===document.referrer||this.N(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=e;this.a.lv=f},ob:function(){for(var a=[],b=this.a.et,d=+new Date,e=0,g=k.ya.length;e<g;e++){var f=k.ya[e],l=this.a[f];"undefined"!==typeof l&&""!==l&&("tt"!==f||"tt"===f&&0===b)&&(("ct"!==f||"ct"===f&&0===b)&&("kb"!==f||"kb"===f&&3===b))&&a.push(f+"="+encodeURIComponent(l))}switch(b){case 0:a.push("sn="+k.z);this.a.rt&&
a.push("rt="+encodeURIComponent(this.a.rt));break;case 3:a.push("sn="+k.z);break;case 5:a.push("sn="+k.z);a.push("_lpt="+this.r);a.push("_ct="+d);break;case 6:a.push("sn="+k.z);a.push("_lpt="+this.r);a.push("_ct="+d);break;case 85:a.push("sn="+k.z);break;case 90:this.a.rt&&a.push("rt="+this.a.rt)}return a.join("&")},qb:function(){this.pb();this.a.si=c.id;this.a.hca=q;this.a.su=document.referrer;this.a.hh=window.location.hash;this.a.ds=n.lb;this.a.cl=n.colorDepth+"-bit";this.a.ln=String(n.language).toLowerCase();
this.a.ja=n.javaEnabled?1:0;this.a.ck=n.cookieEnabled?1:0;this.a.bs=v;this.a.lo="number"===typeof _bdhm_top?1:0;this.a.fl=l.Xa();this.a.v="1.2.42";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.a.tt=document.title||"";this.a.vl=n.M()+n.C();var b=document.location.href;this.a.cm=a.k(b,k.ab)||"";this.a.cp=a.k(b,k.bb)||a.k(b,k.wb)||"";this.a.cw=a.k(b,k.$a)||a.k(b,k.yb)||"";this.a.ci=a.k(b,k.Ya)||a.k(b,k.vb)||"";this.a.cf=a.k(b,k.cb)||a.k(b,k.xb)||"";this.a.cu=a.k(b,k.Za)||a.k(b,k.ub)||
""},init:function(){try{this.qb(),0===this.a.nv?this.nb():this.ha(".*"),h.b=this,this.Ga(),w.J("pv-b"),this.mb()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));d.log(k.da+"//"+k.wa+"?"+b.join("&"))}},mb:function(){function a(){w.J("pv-d")}this.qa?(this.aa=r,this.a.et=0,this.a.ep="",this.a.vl=n.M()+n.C(),this.h(a)):a();this.r=+new Date},h:function(a){if(this.ra){var b=this;b.a.rnd=
Math.round(Math.random()*k.ea);w.J("stag-b");var e=k.da+"//"+k.wa+"?"+b.ob();w.J("stag-d");b.Ba(e);d.log(e,function(d){b.ha(d);f.d(a,"Function")&&a.call(b)})}},Ga:function(){var b=document.location.hash.substring(1),d=RegExp(c.id),e=a.Z(document.referrer)===k.Ca?1:0,f=a.k(b,"jn"),g=/^heatlink$|^select$|^pageclick$/.test(f);b&&(d.test(b)&&e&&g)&&(this.a.rnd=Math.round(Math.random()*k.ea),b=document.createElement("script"),b.setAttribute("type","text/javascript"),b.setAttribute("charset","utf-8"),b.setAttribute("src",
k.protocol+"//"+c.js+f+".js?"+this.a.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(b,f))},Ba:function(a){var b=e.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");e.set("Hm_unsent_"+c.id,b)},ha:function(a){var b=e.get("Hm_unsent_"+c.id)||"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),a=RegExp(a.replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),(b=
b.replace(a,"").replace(/,$/,""))?e.set("Hm_unsent_"+c.id,b):e.remove("Hm_unsent_"+c.id))},nb:function(){var a=this,b=e.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),f=function(b){d.log(k.da+"//"+decodeURIComponent(b),function(b){a.ha(b)})},g=0,l=b.length;g<l;g++)f(b[g])}};return new b})();
(function(){var b=mt.event,a=mt.lang,d=h.o;if(c.kbtrk&&"undefined"!==typeof h.b){h.b.a.kb=a.ta(h.b.a.kb)?h.b.a.kb:0;var l=function(){h.b.a.et=85;h.b.a.ep=h.b.a.kb;h.b.h()};b.c(document,"keyup",function(){h.b.a.kb++});b.c(window,"unload",function(){l()});setInterval(l,d.hb)}})();var B=h.o,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var b=mt.event,a=mt.l;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.b){var d=function(a){var b=performance.timing,d=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:d,end:a,value:0<a-d?a-d:0}},l=function(){var b;b=d("navigation");var f=d("request");b={netAll:f.start-b.start,netDns:d("domainLookup").value,netTcp:d("connect").value,srv:d("response").start-f.start,dom:performance.timing.domInteractive-performance.timing.fetchStart,loadEvent:d("loadEvent").end-
b.start};h.b.a.et=87;h.b.a.ep=a.stringify(b);h.b.h()};b.c(window,"load",function(){setTimeout(l,500)})}}catch(f){}})();
(function(){var b=mt.g,a=mt.lang,d=mt.event,l=mt.l;if("undefined"!==typeof h.b&&(c.med||(!b.sa||7<b.eb)&&c.cvcc)){var f,g,n,m,e=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},k=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===t)return t},v=function(b,d){var e={};e.n=f;e.t="clk";e.v=b;if(d){var g=d.getAttribute("href"),k=d.getAttribute("onclick")?""+d.getAttribute("onclick"):s,m=d.getAttribute("id")||"";n.test(g)?(e.sn="mediate",
e.snv=g):a.d(k,"String")&&n.test(k)&&(e.sn="wrap",e.snv=k);e.id=m}h.b.a.et=86;h.b.a.ep=l.stringify(e);h.b.h();for(e=+new Date;400>=+new Date-e;);};if(c.med)g="/zoosnet",f="swt",n=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,m={click:function(){for(var a=[],b=e(document.getElementsByTagName("a")),b=[].concat.apply(b,e(document.getElementsByTagName("area"))),b=[].concat.apply(b,e(document.getElementsByTagName("img"))),d,f,g=0,k=b.length;g<k;g++)d=b[g],f=d.getAttribute("onclick"),
d=d.getAttribute("href"),(n.test(f)||n.test(d))&&a.push(b[g]);return a}};else if(c.cvcc){g="/other-comm";f="other";n=c.cvcc.q||q;var w=c.cvcc.id||q;m={click:function(){for(var a=[],b=e(document.getElementsByTagName("a")),b=[].concat.apply(b,e(document.getElementsByTagName("area"))),b=[].concat.apply(b,e(document.getElementsByTagName("img"))),d,f,g,k=0,l=b.length;k<l;k++)d=b[k],n!==q?(f=d.getAttribute("onclick"),g=d.getAttribute("href"),w?(d=d.getAttribute("id"),(n.test(f)||n.test(g)||w.test(d))&&
a.push(b[k])):(n.test(f)||n.test(g))&&a.push(b[k])):w!==q&&(d=d.getAttribute("id"),w.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof m&&"undefined"!==typeof n){var p;g+=/\/$/.test(g)?"":"/";var u=function(b,d){if(p===d)return v(g+b,d),t;if(a.d(d,"Array")||a.d(d,"NodeList"))for(var e=0,f=d.length;e<f;e++)if(p===d[e])return v(g+b+"/"+(e+1),d[e]),t};d.c(document,"mousedown",function(b){b=b||window.event;p=b.target||b.srcElement;var d={};for(k(m,function(b,e){d[b]=a.d(e,"Function")?e():document.getElementById(e)});p&&
p!==document&&k(d,u)!==t;)p=p.parentNode})}}})();(function(){var b=mt.e,a=mt.lang,d=mt.event,l=mt.l;if("undefined"!==typeof h.b&&a.d(c.cvcf,"Array")&&0<c.cvcf.length){var f={za:function(){for(var a=c.cvcf.length,l,m=0;m<a;m++)(l=b.Oa(decodeURIComponent(c.cvcf[m])))&&d.c(l,"click",f.Ka())},Ka:function(){return function(){h.b.a.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.b.a.ep=l.stringify(a);h.b.h()}}};b.ib(function(){f.za()})}})();
(function(){var b=mt.event,a=mt.l;if(c.med&&"undefined"!==typeof h.b){var d=+new Date,l={n:"anti",sb:0,kb:0,clk:0},f=function(){h.b.a.et=86;h.b.a.ep=a.stringify(l);h.b.h()};b.c(document,"click",function(){l.clk++});b.c(document,"keyup",function(){l.kb=1});b.c(window,"scroll",function(){l.sb++});b.c(window,"unload",function(){l.t=+new Date-d;f()});b.c(window,"load",function(){setTimeout(f,5E3)})}})();})();
